# ===== Registration =====

ASK_REGISTRATION = "ASK_REGISTRATION"

MAIN_MENU = "MAIN_MENU"

# ===== Consultation =====

WAITING_CONSULTATION = "WAITING_CONSULTATION"

WAITING_AGENT = "WAITING_AGENT"

IN_CONSULTATION = "IN_CONSULTATION"

CONSULTATION_FINISHED = "CONSULTATION_FINISHED"

CONSULTATION_STATUS_WAITING_AGENT = "waiting_agent"

CONSULTATION_STATUS_ACTIVE = "active"

CONSULTATION_STATUS_FINISHED = "finished"