# Registration Step
ASK_REGISTRATION = "ASK_REGISTRATION"
MAIN_MENU = "MAIN_MENU"

# Menu Navigation
PUBLICATION_MENU = "PUBLICATION_MENU"
DATA_MENU = "DATA_MENU"

# Consultation
WAITING_CONSULTATION = "WAITING_CONSULTATION"
WAITING_AGENT = "WAITING_AGENT"

# Consultation Status
CONSULTATION_WAITING = "WAITING_AGENT"
CONSULTATION_ACTIVE = "ACTIVE"
CONSULTATION_FINISHED = "FINISHED"

# User Mode
BOT_MODE = "BOT_MODE"
AGENT_MODE = "AGENT_MODE"